version: "3.8"
services:
  backend:
    build: .
    command: gunicorn core.wsgi --bind 0.0.0.0:8000
    ports:
      - 8000:8000
  frontend:
    build:
      context: ./core-react
    volumes:
      - react_build:/core-react/react_build
  nginx:
    image: nginx:latest
    ports:
      - 80:8080
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf.ro
      - react_build:/var/www/core-react
    depends_on:
      - backend
      - frontend
volumes:
  react_build:

  #   image: app:django-tes
  #   container_name: django_container
  #   depends_on:
  #     - db
  # db:
  #   # image: postgres
  #   # volumes:
  #   #   - ./data/db:/var/lib/postgresql/data
  #   # environment:
  #   #   - POSTGRES_DB=postgres
  #   #   - POSTGRES_USER=postgres
  #   #   - POSTGRES_PASSWORD=postgres
  #   # container_name: postgres_db
  #   image: mysql:5.7
  #   environment:
  #     MYSQL_DATABASE: 'django-app-db'
  #     MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
  #   volumes:
  #     - ./data/mysql/db:/var/lib/mysql
